services:
  backend:
    container_name: backend_node
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      # - DATABASE_URL=${POSTGRES_URL}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DATABASE}
    env_file:
      - .env

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:  # ✅ Add a health check to ensure PostgreSQL is ready before the backend starts
      test: ["CMD", "pg_isready", "-h", "db" , "-p", "5432"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
